* The underlying exception or error passed to our constructor (if any)
*/
protected Throwable throwable = null;
* 1. 기능 :  Returns the throwable that caused this exception, if any.
* 2. 처리 개요 : 발생한 오류를 표현하는 Throwable
*     -
* 3. 주의사항

